personal_website/personal_website/urls.py
from django.contrib import admin
from django.urls import path
from app_personal_website import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('admin_panel/', views.admin_panel, name='admin_panel'),

    path('admin_panel/new_project', views.new_project, name='new_project'),
    path('admin_panel/edit_project', views.edit_project, name='edit_project'),
    path('admin_panel/remove_project/<int:project_id>/', views.remove_project, name='remove_project'),

    path('',views.homepage, name='homepage'),
    path('about/',views.about, name='about'),

    path('projects/', views.project_list, name='project_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),


    path('contact/',views.contact, name='contact'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_website/app_personal_website/models.py
from django.db import models

class ProjectImage(models.Model):
    project_image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.image.name
    
class Tags(models.Model):
    tag_name = models.CharField(max_length=100)

class Project(models.Model):
    project_title = models.CharField(max_length=200, null=True)
    project_tags = models.ManyToManyField(Tags)
    project_images = models.ManyToManyField(ProjectImage)
    project_description = models.CharField(max_length=200, null=True)
    at_home = models.BooleanField(default=False)
    order = models.IntegerField(null=True)

personal_website/app_personal_website/forms.py
from django import forms
from .models import Project, ProjectImage

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    widget = MultipleFileInput

    def clean(self, value, initial):
        return super().clean(value, initial)

class ProjectForm(forms.ModelForm):
    images = MultipleFileField(required=False)

    class Meta:
        model = Project
        fields = ['project_title', 'project_tags', 'project_description', 'project_images']

    def clean_images(self):
        images = self.cleaned_data.get('images')
        if images:
            return [ProjectImage(project_image=image) for image in images]
        return []

personal_website/app_personal_website/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.core.mail import send_mail
from app_personal_website.models import Project, ProjectImage, Tags

def homepage(request):
    projects = Project.objects.all()
    return render(request, 'homepage.html', {'projects': projects})

def about(request):

    return render(request, 'about.html')

def project_list(request):
    projects = Project.objects.all()
    return render(request, 'projects.html', {'projects': projects})

def contact(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        titulo = request.POST.get('titulo')
        mensagem = request.POST.get('mensagem')

        # Verifica se está capturando os dados corretamente
        print(nome, email, titulo, mensagem)

        # Configurar e enviar o email
        send_mail(
            f'{titulo} - Enviado por: {nome}',  # Assunto do email
            f'De: {email}\n\n{mensagem}',  # Corpo da mensagem
            'seu_email@exemplo.com',  # Email do remetente
            ['leony.ferreira95@gmail.com'],  # Lista de destinatários
            fail_silently=False,
        )

        # Redirecionar após o envio do email
        return redirect('homepage')
    return render(request, 'contact.html')


def admin_panel(request):
    projects = Project.objects.all()
    return render(request, 'admin-panel.html', {'projects':projects})

def new_project(request):
    if request.method == 'POST':
        project_title = request.POST.get('project_title')
        project_tags_input = request.POST.get('project_tags')  # Assume que project_tags é uma string de tags separadas por vírgulas
        project_description = request.POST.get('project_description')

        # Crie um novo projeto
        project = Project.objects.create(
            project_title=project_title,
            project_description=project_description
        )

        # Processar as tags
        tag_names = project_tags_input.split(',')  # Separa as tags em uma lista
        for tag_name in tag_names:
            tag_name = tag_name.strip()  # Remove espaços em branco extras
            tag, created = Tags.objects.get_or_create(tag_name=tag_name)
            project.project_tags.add(tag)

        # Processar as imagens
        for image in request.FILES.getlist('images'):
            project_image = ProjectImage(project_image=image)
            project_image.save()
            project.project_images.add(project_image)

        project.save()  # Salva o projeto no banco de dados

        return redirect('project_list')  # Substitua 'projects' pelo nome correto da sua URL

    return render(request, 'new-project.html')

def remove_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    project.delete()
    return redirect('admin_panel')


def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    return render(request, 'project_detail.html', {'project': project})


def edit_project(request):
    return render(request, 'edit-project.html')

personal_website/app_personal_website/templates/about.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Sobre Mim - Leony Coelho</title>
  <main>
    <div class="container">
      <div class="p-5 mb-4">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">Olá,</h1>
          <p class="col-md-8 fs-4">me chamo Leony Coelho e atuo como Desenvolvedor Fullstack e Designer Gráfico. Trabalho na criação de Websites e Aplicações Web, buscando atender diferentes demandas. Além disso, dedico-me à concepção e execução de peças gráficas digitais e identidade visual. Estou aqui para colaborar e agregar valor aos seus projetos.</p>
        </div>
      </div>
      <div class="px-4 py-0" id="icon-grid">
        
        <div class="row">
          
          <div class="row row-cols-1 col-6 g-4 py-5">
            <h2 class="pb-2">Desenvolviment Fullstack</h2>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Site Institucional</h4>
                <p>Um website para sua empresa ou negócio.</p>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Landing Page</h4>
                <p>Uma pagina estática, perfeita para divulgações.</p>
              </div>
            </div>
            <!-- <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Loja Online</h4>
                <p>Uma .</p>
              </div>
            </div> -->
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Aplicação web customizada</h4>
                <p>Aplicações web para solucionar diversas demandas administrativas.</p>
              </div>
            </div>
          </div>
  
          <div class="row row-cols-1 col-6 g-4 py-5">
            <h2 class="pb-2">Design Gráfico</h2>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Identidade Visual</h4>
                <p>A identidade visual é a cara da sua empresa.</p>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Gráfico Digital</h4>
                <p>Peças gráficas para todas as finalidades.</p>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Apresentações Digitais</h4>
                <p>Documentos digitais bem diagramados e.</p>
              </div>
            </div>
            <!-- <div class="col d-flex align-items-start">
              <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
              <div>
                <h4 class="fw-bold mb-0">Peças de Promocionais</h4>
                <p>Paragraph of text beneath the heading to explain the heading.</p>
              </div>
            </div> -->
          </div>

        </div>



      </div>
    

      
    </div>
    
  </main>
  {% endblock %}

personal_website/app_personal_website/templates/admin-panel.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Admin Panel - Leony Coelho</title>
  <main>
    <div class="container">
      <h1>ADMIN PANEL</h1>
      <a href="{% url 'new_project' %}">Novo Projeto</a>
      {% for project in projects %}
      <p> {{project.project_title}} - <a href="{% url 'remove_project' project.id %}">Remove</a></p>
      {% endfor %}
    </div>
  </main>
  {% endblock %}

personal_website/app_personal_website/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pagina pessoal de Leony Coelho">
    <meta name="author" content="Leony Coelho">

    <!-- <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sticky-footer-navbar/"> -->
    
    
    
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
  <link href="sticky-footer-navbar.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    
    <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md ">
        <div class="container-fluid container">
        <a class="yellow-color navbar-brand" href="#">Leony Coelho</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link white-color" aria-current="page" href="{% url 'homepage' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link white-color" href="{% url 'about' %}">Sobre</a>
            </li>
            <li class="nav-item">
              <a class="nav-link white-color" href="{% url 'project_list' %}">Serviços</a>
            </li>
            <li class="nav-item">
              <a class="nav-link white-color" href="{% url 'project_list' %}">Projetos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link white-color" href="{% url 'contact' %}">Contato</a>
            </li>
            <li class="nav-item">
                <a class="nav-link white-color" href="#">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link white-color" href="{% url 'admin_panel' %}">Admin</a>
            </li>
            </ul>
            <div class="d-flex">
              <ul class="navbar-nav me-auto mb-2 mb-md-0" >
                <li class="nav-item" >
                  <a class="nav-link" href="https://github.com/LeonyCoelho" target="_blank" style="color: #ffd401ff;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                    </svg>
                  </a>
                </li>    
                <li class="nav-item">
                  <a class="nav-link" href="https://www.behance.net/leonycoelho" target="_blank" style="color: #ffd401ff;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-behance" viewBox="0 0 16 16">
                      <path d="M4.654 3c.461 0 .887.035 1.278.14.39.07.711.216.996.391.286.176.497.426.641.747.14.32.216.711.216 1.137 0 .496-.106.922-.356 1.242-.215.32-.566.606-.997.817.606.176 1.067.496 1.348.922.281.426.461.957.461 1.563 0 .496-.105.922-.285 1.278a2.317 2.317 0 0 1-.782.887c-.32.215-.711.39-1.137.496a5.329 5.329 0 0 1-1.278.176L0 12.803V3h4.654zm-.285 3.978c.39 0 .71-.105.957-.285.246-.18.355-.497.355-.887 0-.216-.035-.426-.105-.567a.981.981 0 0 0-.32-.355 1.84 1.84 0 0 0-.461-.176c-.176-.035-.356-.035-.567-.035H2.17v2.31c0-.005 2.2-.005 2.2-.005zm.105 4.193c.215 0 .426-.035.606-.07.176-.035.356-.106.496-.216s.25-.215.356-.39c.07-.176.14-.391.14-.641 0-.496-.14-.852-.426-1.102-.285-.215-.676-.32-1.137-.32H2.17v2.734h2.305v.005zm6.858-.035c.286.285.711.426 1.278.426.39 0 .746-.106 1.032-.286.285-.215.46-.426.53-.64h1.74c-.286.851-.712 1.457-1.278 1.848-.566.355-1.243.566-2.06.566a4.135 4.135 0 0 1-1.527-.285 2.827 2.827 0 0 1-1.137-.782 2.851 2.851 0 0 1-.712-1.172c-.175-.461-.25-.957-.25-1.528 0-.531.07-1.032.25-1.493.18-.46.426-.852.747-1.207.32-.32.711-.606 1.137-.782a4.018 4.018 0 0 1 1.493-.285c.606 0 1.137.105 1.598.355.46.25.817.532 1.102.958.285.39.496.851.641 1.348.07.496.105.996.07 1.563h-5.15c0 .58.21 1.11.496 1.396zm2.24-3.732c-.25-.25-.642-.391-1.103-.391-.32 0-.566.07-.781.176-.215.105-.356.25-.496.39a.957.957 0 0 0-.25.497c-.036.175-.07.32-.07.46h3.196c-.07-.526-.25-.882-.497-1.132zm-3.127-3.728h3.978v.957h-3.978v-.957z"/>
                    </svg>
                  </a>
                </li>  
                <li class="nav-item">
                  <a class="nav-link" href="https://www.linkedin.com/in/leony-coelho/" target="_blank" style="color: #ffd401ff;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                      <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                    </svg>
                  </a>
                </li>   




              </ul>
            </div>
        </div>
        </div>
    </nav>
    </header>

{% block content %}
{% endblock %} 

    <footer class="footer mt-auto py-3 ">
    <div class="container">
        <span class="text-muted lead">Desenvolvido por Leony Coelho - 2024.</span>
    </div>
    </footer>
    <!-- <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
  </body>
</html>

personal_website/app_personal_website/templates/contact.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Contato - Leony Coelho</title>
  <main class="contact-main">
    <div class="container">
      <main class="form-contact">

          <div class="row">
            <div class="contact-box col-md-8 mx-auto">
                <h2 class="pb-2  yellow-color">Entre em contato</h2>
                <form method="post" action="{% url 'contact' %}">
                  {% csrf_token %}
                  <div class="form-group row">
                    <div class="mb-3 col-sm-12 col-md-6 col-lg-6">
                        <label hidden>Nome</label>
                        <input type="text" name="nome" placeholder="Nome" class="form-control">
                    </div>
                    <div class="mb-3 col-6 col-sm-12 col-md-6 col-lg-6">
                        <label hidden>Email</label>
                        <input type="email" name="email" placeholder="Email" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label hidden>Título</label>
                        <input type="text" name="titulo" placeholder="Título da mensagem" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label hidden>Mensagem</label>
                        <textarea name="mensagem" placeholder="Sua mensagem" class="form-control user-msg" rows="10"></textarea>
                    </div>
                    <div class="mb-3">
                      <button type="submit" class="btn pink-bg white-color">Enviar</button>
                    </div>
                </div>
                </form>
            </div>
          </div>

      </main>
      


  </div>
  </main>
  {% endblock %}

personal_website/app_personal_website/templates/new-project.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Projetos - Leony Coelho</title>
  <main>
    <h2>Create Project</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="id_project_title">Título do Projeto:</label>
      <input type="text" name="project_title" id="id_project_title" required>
      <br>
    
      <label for="id_project_tags">Tags:</label>
      <input type="text" name="project_tags" id="id_project_tags">
      <br>
    
      <label for="id_project_description">Descrição do Projeto:</label>
      <input type="text" name="project_description" id="id_project_description">
      <br>
    
      <label for="id_images">Imagens:</label>
      <input type="file" name="images" id="id_images" multiple>
      <br>
    
      <input type="submit" value="Salvar Projeto">
    </form>
  </main>
{% endblock %}

personal_website/app_personal_website/templates/project_detail.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Projetos - Leony Coelho</title>
  <main>
   
    <div class="container">
      <h1>{{ project.project_title }}</h1>
      {% for tag in project.project_tags.all %}
        <p class="card-text">{{ tag.tag_name }}</p>
      {% endfor %} 
      {% for image in project.project_images.all %}
      <img class="project-image w-100" src="{{ image.project_image.url }}" alt="{{ image.project_image.url }}"><br>
      {% endfor %}
      <h6 class="lead yellow-color fw-bold mt-3">Detalhes</h6>
      <p class="lead">{{ project.project_description }}</p>
    </div>
    </main>
  {% endblock %}

personal_website/app_personal_website/templates/projects.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  <title>Projetos - Leony Coelho</title>
  <main>
<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="yellow-color">Lista de Projetos</h1>
    </div>
    <div class="col-4">
          <div class="btn-group end-0 d-flex justify-content-end" role="group" aria-label="Tags">
            {% for project in projects %}
              {% for tag in project.project_tags.all %}
                <button type="button" class="btn pink-out text-white no-outline" aria-current="page" href="#" data-tag="{{ tag.tag_name }}">{{ tag.tag_name }}</button>
              {% endfor %}
            {% endfor %}
          </div>
    </div>
  </div>
  
  
  {% for project in projects %}
    <a href="{% url 'project_detail' project.id %}">
      <div class="card bg-dark text-white project-card mb-3">
        {% if project.project_images.all %}
          <img src="{{ project.project_images.all.0.project_image.url }}" class="card-img project-cover" alt="{{ project.project_title }} Image">
        {% endif %}
        <div class="card-img-overlay">
          <h5 class="card-title">{{ project.project_title }}</h5>
          {% if project.project_description %}
            <p class="card-text">{{ project.project_description|safe|slice:":100" }}</p>
          {% endif %}
          {% for tag in project.project_tags.all %}
            <p class="card-text">{{ tag.tag_name }}</p>
          {% endfor %}
        </div>
      </div>
    </a>
  {% endfor %}
</div>
</main>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const tagButtons = document.querySelectorAll(".btn-group button");
    const projectCards = document.querySelectorAll(".project-card");
  
    tagButtons.forEach(function(button) {
      button.addEventListener("click", function(event) {
        event.preventDefault();
  
        const selectedTag = event.target.dataset.tag;
  
        // Desselecionar todos os botões e ocultar todos os projetos
        resetSelection();
  
        // Filtrar os projetos com base na tag
        filterProjects(selectedTag);
  
        // Adicionar classe 'pink-bg' ao botão selecionado
        event.target.classList.add("pink-bg");
      });
    });
  
    function filterProjects(tag) {
      projectCards.forEach(function(card) {
        const projectTags = Array.from(card.querySelectorAll(".card-text"));
  
        // Verificar se a tag está presente nas tags do projeto
        const shouldShow = projectTags.some(function(tagElement) {
          return tagElement.textContent === tag;
        });
  
        // Exibir ou ocultar o projeto com base na filtragem
        card.style.display = shouldShow ? "block" : "none";
      });
    }
  
    function resetSelection() {
      // Desselecionar todos os botões do grupo
      tagButtons.forEach(function(button) {
        button.classList.remove("pink-bg");
      });
  
      // Ocultar todos os projetos
      projectCards.forEach(function(card) {
        card.style.display = "none";
      });
    }
  });
</script>



  {% endblock %}